namespace AquaTrack.Pages.Input_Forms
{
    partial class ReportForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ReportForm));
            siticoneLabelReportDetails = new SiticoneNetCoreUI.SiticoneLabel();
            siticoneLabelReportType = new SiticoneNetCoreUI.SiticoneLabel();
            siticoneDropdownReportType = new SiticoneNetCoreUI.SiticoneDropdown();
            siticoneLabelReportRangeDate = new SiticoneNetCoreUI.SiticoneLabel();
            siticoneDateTimePickerReportStartDate = new SiticoneNetCoreUI.SiticoneDateTimePicker();
            siticoneButtonReportGenerate = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButtonExportReport = new SiticoneNetCoreUI.SiticoneButton();
            siticoneButtonReportCancel = new SiticoneNetCoreUI.SiticoneButton();
            siticoneLabelReportSummary = new SiticoneNetCoreUI.SiticoneLabel();
            siticoneDGVReportSummary = new SiticoneNetCoreUI.SiticoneDataGridView();
            siticoneTextBoxReportTitle = new SiticoneNetCoreUI.SiticoneTextBox();
            siticoneLabelReportTitle = new SiticoneNetCoreUI.SiticoneLabel();
            siticoneDateTimePickerReportEndDate = new SiticoneNetCoreUI.SiticoneDateTimePicker();
            siticoneLabelEndDate = new SiticoneNetCoreUI.SiticoneLabel();
            siticoneMaterialRadioButtonDaily = new SiticoneNetCoreUI.SiticoneMaterialRadioButton();
            siticoneMaterialRadioButtonMonthlyYearly = new SiticoneNetCoreUI.SiticoneMaterialRadioButton();
            ((System.ComponentModel.ISupportInitialize)siticoneDGVReportSummary).BeginInit();
            SuspendLayout();
            // 
            // siticoneLabelReportDetails
            // 
            siticoneLabelReportDetails.BackColor = Color.Transparent;
            siticoneLabelReportDetails.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneLabelReportDetails.Location = new Point(9, 9);
            siticoneLabelReportDetails.Name = "siticoneLabelReportDetails";
            siticoneLabelReportDetails.Size = new Size(100, 23);
            siticoneLabelReportDetails.TabIndex = 0;
            siticoneLabelReportDetails.Text = "Report Details";
            // 
            // siticoneLabelReportType
            // 
            siticoneLabelReportType.BackColor = Color.Transparent;
            siticoneLabelReportType.Font = new Font("Segoe UI", 10F);
            siticoneLabelReportType.Location = new Point(48, 132);
            siticoneLabelReportType.Name = "siticoneLabelReportType";
            siticoneLabelReportType.Size = new Size(100, 23);
            siticoneLabelReportType.TabIndex = 2;
            siticoneLabelReportType.Text = "Report Type";
            // 
            // siticoneDropdownReportType
            // 
            siticoneDropdownReportType.AllowMultipleSelection = false;
            siticoneDropdownReportType.BackColor = Color.White;
            siticoneDropdownReportType.BorderColor = Color.FromArgb(180, 180, 180);
            siticoneDropdownReportType.CanBeep = false;
            siticoneDropdownReportType.CanShake = true;
            siticoneDropdownReportType.DataSource = null;
            siticoneDropdownReportType.DisplayMember = null;
            siticoneDropdownReportType.DropdownBackColor = Color.White;
            siticoneDropdownReportType.DropdownWidth = 0;
            siticoneDropdownReportType.DropShadowEnabled = false;
            siticoneDropdownReportType.Font = new Font("Segoe UI", 10F);
            siticoneDropdownReportType.ForeColor = Color.FromArgb(60, 60, 60);
            siticoneDropdownReportType.HoveredItemBackColor = Color.FromArgb(240, 240, 240);
            siticoneDropdownReportType.HoveredItemTextColor = Color.FromArgb(30, 30, 30);
            siticoneDropdownReportType.IsReadonly = false;
            siticoneDropdownReportType.ItemHeight = 30;
            siticoneDropdownReportType.Items.AddRange(new string[] { "Product", "Sales", "Damage and Casualties" });
            siticoneDropdownReportType.Location = new Point(48, 158);
            siticoneDropdownReportType.MaxDropDownItems = 8;
            siticoneDropdownReportType.Name = "siticoneDropdownReportType";
            siticoneDropdownReportType.PlaceholderColor = Color.Gray;
            siticoneDropdownReportType.PlaceholderDisappearsOnFocus = false;
            siticoneDropdownReportType.PlaceholderText = "Select an option";
            siticoneDropdownReportType.SelectedIndex = -1;
            siticoneDropdownReportType.SelectedItem = null;
            siticoneDropdownReportType.SelectedItemBackColor = Color.FromArgb(230, 240, 250);
            siticoneDropdownReportType.SelectedItemTextColor = Color.FromArgb(30, 30, 30);
            siticoneDropdownReportType.SelectedValue = null;
            siticoneDropdownReportType.Size = new Size(275, 40);
            siticoneDropdownReportType.TabIndex = 3;
            siticoneDropdownReportType.Text = "siticoneDropdownReportType";
            siticoneDropdownReportType.UnselectedItemTextColor = Color.FromArgb(60, 60, 60);
            siticoneDropdownReportType.ValueMember = null;
            // 
            // siticoneLabelReportRangeDate
            // 
            siticoneLabelReportRangeDate.BackColor = Color.Transparent;
            siticoneLabelReportRangeDate.Font = new Font("Segoe UI", 10F);
            siticoneLabelReportRangeDate.Location = new Point(48, 256);
            siticoneLabelReportRangeDate.Name = "siticoneLabelReportRangeDate";
            siticoneLabelReportRangeDate.Size = new Size(141, 23);
            siticoneLabelReportRangeDate.TabIndex = 4;
            siticoneLabelReportRangeDate.Text = "Report Range / Date";
            // 
            // siticoneDateTimePickerReportStartDate
            // 
            siticoneDateTimePickerReportStartDate.AutoScaleFonts = true;
            siticoneDateTimePickerReportStartDate.BackColor = Color.Transparent;
            siticoneDateTimePickerReportStartDate.BaseCalendarFormSize = new Size(535, 460);
            siticoneDateTimePickerReportStartDate.BorderColor = Color.FromArgb(180, 180, 180);
            siticoneDateTimePickerReportStartDate.BorderWidth = 2;
            siticoneDateTimePickerReportStartDate.BottomLeftBorderRadius = 8;
            siticoneDateTimePickerReportStartDate.BottomRightBorderRadius = 8;
            siticoneDateTimePickerReportStartDate.CalendarBackgroundColor = Color.White;
            siticoneDateTimePickerReportStartDate.CalendarChevronColor = Color.Gray;
            siticoneDateTimePickerReportStartDate.CalendarChevronHoverColor = Color.Blue;
            siticoneDateTimePickerReportStartDate.CalendarDayButtonBackColor = Color.White;
            siticoneDateTimePickerReportStartDate.CalendarDayButtonForeColor = Color.Black;
            siticoneDateTimePickerReportStartDate.CalendarDayHeaderBackColor = Color.White;
            siticoneDateTimePickerReportStartDate.CalendarDayHeaderForeColor = Color.FromArgb(100, 100, 100);
            siticoneDateTimePickerReportStartDate.CalendarDayLabelFont = new Font("Segoe UI", 10F, FontStyle.Bold);
            siticoneDateTimePickerReportStartDate.CalendarDisabledDateBackColor = Color.LightGray;
            siticoneDateTimePickerReportStartDate.CalendarDisabledDateForeColor = Color.DarkGray;
            siticoneDateTimePickerReportStartDate.CalendarFormAnimationSpeed = 15;
            siticoneDateTimePickerReportStartDate.CalendarFormAnimationStep = 0.08D;
            siticoneDateTimePickerReportStartDate.CalendarFormBackColor = Color.White;
            siticoneDateTimePickerReportStartDate.CalendarFormBorderColor = Color.FromArgb(220, 220, 220);
            siticoneDateTimePickerReportStartDate.CalendarFormBorderWidth = 2;
            siticoneDateTimePickerReportStartDate.CalendarFormCornerRadius = 2;
            siticoneDateTimePickerReportStartDate.CalendarFormFadeOutStep = 0.1D;
            siticoneDateTimePickerReportStartDate.CalendarFormHeight = 460;
            siticoneDateTimePickerReportStartDate.CalendarFormShadowColor = Color.FromArgb(50, 0, 0, 0);
            siticoneDateTimePickerReportStartDate.CalendarFormShadowDepth = 5;
            siticoneDateTimePickerReportStartDate.CalendarFormWidth = 535;
            siticoneDateTimePickerReportStartDate.CalendarGridMargin = new Padding(8);
            siticoneDateTimePickerReportStartDate.CalendarGridPadding = new Padding(5);
            siticoneDateTimePickerReportStartDate.CalendarLockedDateBackColor = Color.LightGray;
            siticoneDateTimePickerReportStartDate.CalendarLockedDateForeColor = Color.DarkGray;
            siticoneDateTimePickerReportStartDate.CalendarLockedDates = (List<DateTime>)resources.GetObject("siticoneDateTimePickerReportStartDate.CalendarLockedDates");
            siticoneDateTimePickerReportStartDate.CalendarMargin = 5;
            siticoneDateTimePickerReportStartDate.CalendarMaxDate = new DateTime(9998, 12, 31, 0, 0, 0, 0);
            siticoneDateTimePickerReportStartDate.CalendarMaxYear = 2125;
            siticoneDateTimePickerReportStartDate.CalendarMinDate = new DateTime(1753, 1, 1, 0, 0, 0, 0);
            siticoneDateTimePickerReportStartDate.CalendarMinYear = 1925;
            siticoneDateTimePickerReportStartDate.CalendarRangeDateBackColor = Color.LightBlue;
            siticoneDateTimePickerReportStartDate.CalendarRangeEndDateBackColor = Color.DodgerBlue;
            siticoneDateTimePickerReportStartDate.CalendarRangeSelectedForeColor = Color.Black;
            siticoneDateTimePickerReportStartDate.CalendarRangeStartDateBackColor = Color.DodgerBlue;
            siticoneDateTimePickerReportStartDate.CalendarSelectedDateBackColor = Color.FromArgb(0, 120, 215);
            siticoneDateTimePickerReportStartDate.CalendarSelectedDateForeColor = Color.White;
            siticoneDateTimePickerReportStartDate.CalendarSelectionMode = SiticoneNetCoreUI.SelectionMode.Range;
            siticoneDateTimePickerReportStartDate.CalendarTodayBackColor = Color.White;
            siticoneDateTimePickerReportStartDate.CalendarTodayForeColor = Color.Black;
            siticoneDateTimePickerReportStartDate.CalendarYearPickerHeight = 10;
            siticoneDateTimePickerReportStartDate.CanBeep = true;
            siticoneDateTimePickerReportStartDate.CanShake = true;
            siticoneDateTimePickerReportStartDate.ChevronColor = Color.FromArgb(100, 100, 100);
            siticoneDateTimePickerReportStartDate.ChevronHoverBackColor = Color.FromArgb(220, 225, 245);
            siticoneDateTimePickerReportStartDate.ChevronHoverColor = Color.FromArgb(50, 50, 50);
            siticoneDateTimePickerReportStartDate.ChevronPanelBorderRadius = 0;
            siticoneDateTimePickerReportStartDate.ChevronPanelHeight = 32;
            siticoneDateTimePickerReportStartDate.ChevronPenThickness = 1.8F;
            siticoneDateTimePickerReportStartDate.ChevronRightMargin = 18;
            siticoneDateTimePickerReportStartDate.ChevronSize = new Size(9, 14);
            siticoneDateTimePickerReportStartDate.ChevronStep = 15F;
            siticoneDateTimePickerReportStartDate.ChevronTimerInterval = 15;
            siticoneDateTimePickerReportStartDate.ClearIconColor = Color.Gray;
            siticoneDateTimePickerReportStartDate.ClearIconHoverColor = Color.Red;
            siticoneDateTimePickerReportStartDate.ClearIconRightMargin = 48;
            siticoneDateTimePickerReportStartDate.ClearIconSize = 11;
            siticoneDateTimePickerReportStartDate.ContainerPanelMargin = new Padding(5);
            siticoneDateTimePickerReportStartDate.ContainerPanelPadding = new Padding(0);
            siticoneDateTimePickerReportStartDate.CustomDateFormat = "d";
            siticoneDateTimePickerReportStartDate.CustomDateFormatter = null;
            siticoneDateTimePickerReportStartDate.DateFormat = SiticoneNetCoreUI.DateFormat.LongDate;
            siticoneDateTimePickerReportStartDate.DayButtonBorderRadius = 0;
            siticoneDateTimePickerReportStartDate.DayButtonClickBackColor = Color.FromArgb(220, 230, 250);
            siticoneDateTimePickerReportStartDate.DayButtonFont = new Font("Segoe UI", 10.5F);
            siticoneDateTimePickerReportStartDate.DayButtonHoverBackColor = Color.FromArgb(240, 245, 255);
            siticoneDateTimePickerReportStartDate.DayButtonHoverForeColor = Color.Black;
            siticoneDateTimePickerReportStartDate.DayButtonMargin = new Padding(3);
            siticoneDateTimePickerReportStartDate.DayButtonRowHeight = 16.66F;
            siticoneDateTimePickerReportStartDate.DayHeaderFont = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            siticoneDateTimePickerReportStartDate.DayHeaderForeColor = Color.FromArgb(100, 100, 100);
            siticoneDateTimePickerReportStartDate.DayHeaderMargin = new Padding(1, 1, 1, 8);
            siticoneDateTimePickerReportStartDate.DayHeaderRowHeight = 30F;
            siticoneDateTimePickerReportStartDate.DisabledDayFont = new Font("Segoe UI", 10F, FontStyle.Italic);
            siticoneDateTimePickerReportStartDate.DropdownBackColor = Color.White;
            siticoneDateTimePickerReportStartDate.DropdownFont = new Font("Segoe UI", 11F);
            siticoneDateTimePickerReportStartDate.DropdownHeight = 250;
            siticoneDateTimePickerReportStartDate.FillColor = Color.White;
            siticoneDateTimePickerReportStartDate.FirstDayOfWeek = DayOfWeek.Sunday;
            siticoneDateTimePickerReportStartDate.Font = new Font("Segoe UI", 10F);
            siticoneDateTimePickerReportStartDate.ForeColor = Color.FromArgb(50, 50, 50);
            siticoneDateTimePickerReportStartDate.GradientEndColor = Color.Gray;
            siticoneDateTimePickerReportStartDate.GradientStartColor = Color.White;
            siticoneDateTimePickerReportStartDate.HighlightWeekends = true;
            siticoneDateTimePickerReportStartDate.IconSize = 16;
            siticoneDateTimePickerReportStartDate.IsReadonly = false;
            siticoneDateTimePickerReportStartDate.Location = new Point(48, 282);
            siticoneDateTimePickerReportStartDate.LockedDates = (List<DateTime>)resources.GetObject("siticoneDateTimePickerReportStartDate.LockedDates");
            siticoneDateTimePickerReportStartDate.MakeRadial = false;
            siticoneDateTimePickerReportStartDate.MaxDate = new DateTime(9998, 12, 31, 0, 0, 0, 0);
            siticoneDateTimePickerReportStartDate.MaxFontScale = 1.8F;
            siticoneDateTimePickerReportStartDate.MinDate = new DateTime(1753, 1, 1, 0, 0, 0, 0);
            siticoneDateTimePickerReportStartDate.MinFontScale = 0.4F;
            siticoneDateTimePickerReportStartDate.MinimumFormSize = new Size(150, 150);
            siticoneDateTimePickerReportStartDate.MonthChevronPanelMargin = new Padding(4, 17, 4, 0);
            siticoneDateTimePickerReportStartDate.MonthChevronSpacing = 5;
            siticoneDateTimePickerReportStartDate.MonthComboBoxMargin = new Padding(0, 17, 5, 0);
            siticoneDateTimePickerReportStartDate.MonthComboBoxSize = new Size(130, 30);
            siticoneDateTimePickerReportStartDate.Name = "siticoneDateTimePickerReportStartDate";
            siticoneDateTimePickerReportStartDate.NavigationFlowPadding = new Padding(12, 0, 12, 0);
            siticoneDateTimePickerReportStartDate.NavigationPanelBackColor = Color.FromArgb(245, 245, 245);
            siticoneDateTimePickerReportStartDate.NavigationPanelHeight = 65;
            siticoneDateTimePickerReportStartDate.NextMonthPanelWidth = 34;
            siticoneDateTimePickerReportStartDate.NextYearPanelWidth = 40;
            siticoneDateTimePickerReportStartDate.PlaceholderText = "Select a date...";
            siticoneDateTimePickerReportStartDate.PrevMonthPanelWidth = 34;
            siticoneDateTimePickerReportStartDate.PrevYearPanelWidth = 40;
            siticoneDateTimePickerReportStartDate.RangeStartEndCornerRadius = 0;
            siticoneDateTimePickerReportStartDate.ReadonlyBorderColor = Color.Gray;
            siticoneDateTimePickerReportStartDate.ReadonlyFillColor = Color.LightGray;
            siticoneDateTimePickerReportStartDate.ReadOnlyForeColor = Color.DarkGray;
            siticoneDateTimePickerReportStartDate.ReadonlyPlaceHolderColor = Color.DarkGray;
            siticoneDateTimePickerReportStartDate.SelectedDate = null;
            siticoneDateTimePickerReportStartDate.SelectedDateBorderColor = Color.Black;
            siticoneDateTimePickerReportStartDate.SelectedDateBorderThickness = 1F;
            siticoneDateTimePickerReportStartDate.SelectedDates = (List<DateTime>)resources.GetObject("siticoneDateTimePickerReportStartDate.SelectedDates");
            siticoneDateTimePickerReportStartDate.SelectionMode = SiticoneNetCoreUI.SelectionMode.Range;
            siticoneDateTimePickerReportStartDate.ShakeAmplitude = 4;
            siticoneDateTimePickerReportStartDate.ShakeTimerInterval = 30;
            siticoneDateTimePickerReportStartDate.ShakeTotalShakes = 8;
            siticoneDateTimePickerReportStartDate.ShowClearButton = true;
            siticoneDateTimePickerReportStartDate.ShowMonthYearNavigation = true;
            siticoneDateTimePickerReportStartDate.ShowTodayButton = true;
            siticoneDateTimePickerReportStartDate.Size = new Size(275, 45);
            siticoneDateTimePickerReportStartDate.TabIndex = 5;
            siticoneDateTimePickerReportStartDate.Text = "siticoneDateTimePickerStartDate";
            siticoneDateTimePickerReportStartDate.TodayBorderColor = Color.Black;
            siticoneDateTimePickerReportStartDate.TodayBorderThickness = 2F;
            siticoneDateTimePickerReportStartDate.TodayButtonBackColor = Color.FromArgb(0, 120, 215);
            siticoneDateTimePickerReportStartDate.TodayButtonBorderRadius = 0;
            siticoneDateTimePickerReportStartDate.TodayButtonClickBackColor = Color.Black;
            siticoneDateTimePickerReportStartDate.TodayButtonFont = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            siticoneDateTimePickerReportStartDate.TodayButtonForeColor = Color.White;
            siticoneDateTimePickerReportStartDate.TodayButtonHoverBackColor = Color.FromArgb(0, 100, 190);
            siticoneDateTimePickerReportStartDate.TodayButtonMargin = new Padding(0, 17, 15, 0);
            siticoneDateTimePickerReportStartDate.TodayButtonSize = new Size(70, 35);
            siticoneDateTimePickerReportStartDate.TodayButtonText = "Today";
            siticoneDateTimePickerReportStartDate.TodayTextColor = Color.Black;
            siticoneDateTimePickerReportStartDate.TodayTextFont = new Font("Segoe UI", 10F, FontStyle.Bold);
            siticoneDateTimePickerReportStartDate.TopLeftBorderRadius = 8;
            siticoneDateTimePickerReportStartDate.TopRightBorderRadius = 8;
            siticoneDateTimePickerReportStartDate.UseCalendarFormAnimation = true;
            siticoneDateTimePickerReportStartDate.UseCalendarFormShadow = true;
            siticoneDateTimePickerReportStartDate.UseChevronAnimation = true;
            siticoneDateTimePickerReportStartDate.UseGradientFill = false;
            siticoneDateTimePickerReportStartDate.Value = null;
            siticoneDateTimePickerReportStartDate.WeekendDayBackColor = Color.FromArgb(250, 250, 250);
            siticoneDateTimePickerReportStartDate.WeekendDayForeColor = Color.FromArgb(180, 0, 0);
            siticoneDateTimePickerReportStartDate.YearChevronPanelMargin = new Padding(4, 17, 4, 0);
            siticoneDateTimePickerReportStartDate.YearChevronSpacing = 1;
            siticoneDateTimePickerReportStartDate.YearComboBoxMargin = new Padding(5, 17, 0, 0);
            siticoneDateTimePickerReportStartDate.YearComboBoxSize = new Size(90, 30);
            // 
            // siticoneButtonReportGenerate
            // 
            siticoneButtonReportGenerate.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButtonReportGenerate.AccessibleName = "Generate";
            siticoneButtonReportGenerate.AutoSizeBasedOnText = false;
            siticoneButtonReportGenerate.BackColor = Color.Transparent;
            siticoneButtonReportGenerate.BadgeBackColor = Color.Black;
            siticoneButtonReportGenerate.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButtonReportGenerate.BadgeValue = 0;
            siticoneButtonReportGenerate.BadgeValueForeColor = Color.White;
            siticoneButtonReportGenerate.BorderColor = Color.FromArgb(213, 216, 220);
            siticoneButtonReportGenerate.BorderWidth = 1;
            siticoneButtonReportGenerate.ButtonBackColor = Color.FromArgb(192, 255, 192);
            siticoneButtonReportGenerate.ButtonImage = null;
            siticoneButtonReportGenerate.ButtonTextLeftPadding = 0;
            siticoneButtonReportGenerate.CanBeep = true;
            siticoneButtonReportGenerate.CanGlow = false;
            siticoneButtonReportGenerate.CanShake = true;
            siticoneButtonReportGenerate.ContextMenuStripEx = null;
            siticoneButtonReportGenerate.CornerRadiusBottomLeft = 6;
            siticoneButtonReportGenerate.CornerRadiusBottomRight = 6;
            siticoneButtonReportGenerate.CornerRadiusTopLeft = 6;
            siticoneButtonReportGenerate.CornerRadiusTopRight = 6;
            siticoneButtonReportGenerate.CustomCursor = Cursors.Default;
            siticoneButtonReportGenerate.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButtonReportGenerate.EnableLongPress = false;
            siticoneButtonReportGenerate.EnableRippleEffect = true;
            siticoneButtonReportGenerate.EnableShadow = false;
            siticoneButtonReportGenerate.EnableTextWrapping = false;
            siticoneButtonReportGenerate.Font = new Font("Segoe UI Semibold", 10.2F);
            siticoneButtonReportGenerate.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButtonReportGenerate.GlowIntensity = 100;
            siticoneButtonReportGenerate.GlowRadius = 20F;
            siticoneButtonReportGenerate.GradientBackground = false;
            siticoneButtonReportGenerate.GradientColor = Color.FromArgb(0, 227, 64);
            siticoneButtonReportGenerate.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButtonReportGenerate.HintText = null;
            siticoneButtonReportGenerate.HoverBackColor = Color.FromArgb(240, 240, 240);
            siticoneButtonReportGenerate.HoverFontStyle = FontStyle.Regular;
            siticoneButtonReportGenerate.HoverTextColor = Color.FromArgb(0, 0, 0);
            siticoneButtonReportGenerate.HoverTransitionDuration = 250;
            siticoneButtonReportGenerate.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButtonReportGenerate.ImagePadding = 5;
            siticoneButtonReportGenerate.ImageSize = new Size(16, 16);
            siticoneButtonReportGenerate.IsRadial = false;
            siticoneButtonReportGenerate.IsReadOnly = false;
            siticoneButtonReportGenerate.IsToggleButton = false;
            siticoneButtonReportGenerate.IsToggled = false;
            siticoneButtonReportGenerate.Location = new Point(48, 430);
            siticoneButtonReportGenerate.LongPressDurationMS = 1000;
            siticoneButtonReportGenerate.Name = "siticoneButtonReportGenerate";
            siticoneButtonReportGenerate.NormalFontStyle = FontStyle.Regular;
            siticoneButtonReportGenerate.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButtonReportGenerate.ParticleCount = 15;
            siticoneButtonReportGenerate.PressAnimationScale = 0.97F;
            siticoneButtonReportGenerate.PressedBackColor = Color.FromArgb(225, 227, 230);
            siticoneButtonReportGenerate.PressedFontStyle = FontStyle.Regular;
            siticoneButtonReportGenerate.PressTransitionDuration = 150;
            siticoneButtonReportGenerate.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButtonReportGenerate.RippleColor = Color.FromArgb(0, 0, 0);
            siticoneButtonReportGenerate.RippleRadiusMultiplier = 0.6F;
            siticoneButtonReportGenerate.ShadowBlur = 5;
            siticoneButtonReportGenerate.ShadowColor = Color.FromArgb(30, 0, 0, 0);
            siticoneButtonReportGenerate.ShadowOffset = new Point(0, 2);
            siticoneButtonReportGenerate.ShakeDuration = 500;
            siticoneButtonReportGenerate.ShakeIntensity = 5;
            siticoneButtonReportGenerate.Size = new Size(275, 39);
            siticoneButtonReportGenerate.TabIndex = 6;
            siticoneButtonReportGenerate.Text = "Generate";
            siticoneButtonReportGenerate.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButtonReportGenerate.TextColor = Color.FromArgb(0, 0, 0);
            siticoneButtonReportGenerate.TooltipText = null;
            siticoneButtonReportGenerate.UseAdvancedRendering = true;
            siticoneButtonReportGenerate.UseParticles = false;
            siticoneButtonReportGenerate.Click += siticoneButtonReportGenerate_Click;
            // 
            // siticoneButtonExportReport
            // 
            siticoneButtonExportReport.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButtonExportReport.AccessibleName = "Export to PDF";
            siticoneButtonExportReport.AutoSizeBasedOnText = false;
            siticoneButtonExportReport.BackColor = Color.Transparent;
            siticoneButtonExportReport.BadgeBackColor = Color.Black;
            siticoneButtonExportReport.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButtonExportReport.BadgeValue = 0;
            siticoneButtonExportReport.BadgeValueForeColor = Color.White;
            siticoneButtonExportReport.BorderColor = Color.FromArgb(213, 216, 220);
            siticoneButtonExportReport.BorderWidth = 1;
            siticoneButtonExportReport.ButtonBackColor = Color.FromArgb(128, 255, 128);
            siticoneButtonExportReport.ButtonImage = null;
            siticoneButtonExportReport.ButtonTextLeftPadding = 0;
            siticoneButtonExportReport.CanBeep = true;
            siticoneButtonExportReport.CanGlow = false;
            siticoneButtonExportReport.CanShake = true;
            siticoneButtonExportReport.ContextMenuStripEx = null;
            siticoneButtonExportReport.CornerRadiusBottomLeft = 6;
            siticoneButtonExportReport.CornerRadiusBottomRight = 6;
            siticoneButtonExportReport.CornerRadiusTopLeft = 6;
            siticoneButtonExportReport.CornerRadiusTopRight = 6;
            siticoneButtonExportReport.CustomCursor = Cursors.Default;
            siticoneButtonExportReport.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButtonExportReport.EnableLongPress = false;
            siticoneButtonExportReport.EnableRippleEffect = true;
            siticoneButtonExportReport.EnableShadow = false;
            siticoneButtonExportReport.EnableTextWrapping = false;
            siticoneButtonExportReport.Font = new Font("Segoe UI Semibold", 10.2F);
            siticoneButtonExportReport.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButtonExportReport.GlowIntensity = 100;
            siticoneButtonExportReport.GlowRadius = 20F;
            siticoneButtonExportReport.GradientBackground = false;
            siticoneButtonExportReport.GradientColor = Color.FromArgb(0, 227, 64);
            siticoneButtonExportReport.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButtonExportReport.HintText = null;
            siticoneButtonExportReport.HoverBackColor = Color.FromArgb(240, 240, 240);
            siticoneButtonExportReport.HoverFontStyle = FontStyle.Regular;
            siticoneButtonExportReport.HoverTextColor = Color.FromArgb(0, 0, 0);
            siticoneButtonExportReport.HoverTransitionDuration = 250;
            siticoneButtonExportReport.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButtonExportReport.ImagePadding = 5;
            siticoneButtonExportReport.ImageSize = new Size(16, 16);
            siticoneButtonExportReport.IsRadial = false;
            siticoneButtonExportReport.IsReadOnly = false;
            siticoneButtonExportReport.IsToggleButton = false;
            siticoneButtonExportReport.IsToggled = false;
            siticoneButtonExportReport.Location = new Point(48, 475);
            siticoneButtonExportReport.LongPressDurationMS = 1000;
            siticoneButtonExportReport.Name = "siticoneButtonExportReport";
            siticoneButtonExportReport.NormalFontStyle = FontStyle.Regular;
            siticoneButtonExportReport.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButtonExportReport.ParticleCount = 15;
            siticoneButtonExportReport.PressAnimationScale = 0.97F;
            siticoneButtonExportReport.PressedBackColor = Color.FromArgb(225, 227, 230);
            siticoneButtonExportReport.PressedFontStyle = FontStyle.Regular;
            siticoneButtonExportReport.PressTransitionDuration = 150;
            siticoneButtonExportReport.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButtonExportReport.RippleColor = Color.FromArgb(0, 0, 0);
            siticoneButtonExportReport.RippleRadiusMultiplier = 0.6F;
            siticoneButtonExportReport.ShadowBlur = 5;
            siticoneButtonExportReport.ShadowColor = Color.FromArgb(30, 0, 0, 0);
            siticoneButtonExportReport.ShadowOffset = new Point(0, 2);
            siticoneButtonExportReport.ShakeDuration = 500;
            siticoneButtonExportReport.ShakeIntensity = 5;
            siticoneButtonExportReport.Size = new Size(275, 39);
            siticoneButtonExportReport.TabIndex = 7;
            siticoneButtonExportReport.Text = "Export to PDF";
            siticoneButtonExportReport.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButtonExportReport.TextColor = Color.FromArgb(0, 0, 0);
            siticoneButtonExportReport.TooltipText = null;
            siticoneButtonExportReport.UseAdvancedRendering = true;
            siticoneButtonExportReport.UseParticles = false;
            siticoneButtonExportReport.Click += siticoneButtonExportReport_Click;
            // 
            // siticoneButtonReportCancel
            // 
            siticoneButtonReportCancel.AccessibleDescription = "The default button control that accept input though the mouse, touch and keyboard";
            siticoneButtonReportCancel.AccessibleName = "Cancel";
            siticoneButtonReportCancel.AutoSizeBasedOnText = false;
            siticoneButtonReportCancel.BackColor = Color.Transparent;
            siticoneButtonReportCancel.BadgeBackColor = Color.Black;
            siticoneButtonReportCancel.BadgeFont = new Font("Segoe UI", 8F, FontStyle.Bold);
            siticoneButtonReportCancel.BadgeValue = 0;
            siticoneButtonReportCancel.BadgeValueForeColor = Color.White;
            siticoneButtonReportCancel.BorderColor = Color.FromArgb(213, 216, 220);
            siticoneButtonReportCancel.BorderWidth = 1;
            siticoneButtonReportCancel.ButtonBackColor = Color.FromArgb(255, 192, 192);
            siticoneButtonReportCancel.ButtonImage = null;
            siticoneButtonReportCancel.ButtonTextLeftPadding = 0;
            siticoneButtonReportCancel.CanBeep = true;
            siticoneButtonReportCancel.CanGlow = false;
            siticoneButtonReportCancel.CanShake = true;
            siticoneButtonReportCancel.ContextMenuStripEx = null;
            siticoneButtonReportCancel.CornerRadiusBottomLeft = 6;
            siticoneButtonReportCancel.CornerRadiusBottomRight = 6;
            siticoneButtonReportCancel.CornerRadiusTopLeft = 6;
            siticoneButtonReportCancel.CornerRadiusTopRight = 6;
            siticoneButtonReportCancel.CustomCursor = Cursors.Default;
            siticoneButtonReportCancel.DisabledTextColor = Color.FromArgb(150, 150, 150);
            siticoneButtonReportCancel.EnableLongPress = false;
            siticoneButtonReportCancel.EnableRippleEffect = true;
            siticoneButtonReportCancel.EnableShadow = false;
            siticoneButtonReportCancel.EnableTextWrapping = false;
            siticoneButtonReportCancel.Font = new Font("Segoe UI Semibold", 10.2F);
            siticoneButtonReportCancel.GlowColor = Color.FromArgb(100, 255, 255, 255);
            siticoneButtonReportCancel.GlowIntensity = 100;
            siticoneButtonReportCancel.GlowRadius = 20F;
            siticoneButtonReportCancel.GradientBackground = false;
            siticoneButtonReportCancel.GradientColor = Color.FromArgb(0, 227, 64);
            siticoneButtonReportCancel.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            siticoneButtonReportCancel.HintText = null;
            siticoneButtonReportCancel.HoverBackColor = Color.FromArgb(240, 240, 240);
            siticoneButtonReportCancel.HoverFontStyle = FontStyle.Regular;
            siticoneButtonReportCancel.HoverTextColor = Color.FromArgb(0, 0, 0);
            siticoneButtonReportCancel.HoverTransitionDuration = 250;
            siticoneButtonReportCancel.ImageAlign = ContentAlignment.MiddleLeft;
            siticoneButtonReportCancel.ImagePadding = 5;
            siticoneButtonReportCancel.ImageSize = new Size(16, 16);
            siticoneButtonReportCancel.IsRadial = false;
            siticoneButtonReportCancel.IsReadOnly = false;
            siticoneButtonReportCancel.IsToggleButton = false;
            siticoneButtonReportCancel.IsToggled = false;
            siticoneButtonReportCancel.Location = new Point(48, 520);
            siticoneButtonReportCancel.LongPressDurationMS = 1000;
            siticoneButtonReportCancel.Name = "siticoneButtonReportCancel";
            siticoneButtonReportCancel.NormalFontStyle = FontStyle.Regular;
            siticoneButtonReportCancel.ParticleColor = Color.FromArgb(200, 200, 200);
            siticoneButtonReportCancel.ParticleCount = 15;
            siticoneButtonReportCancel.PressAnimationScale = 0.97F;
            siticoneButtonReportCancel.PressedBackColor = Color.FromArgb(225, 227, 230);
            siticoneButtonReportCancel.PressedFontStyle = FontStyle.Regular;
            siticoneButtonReportCancel.PressTransitionDuration = 150;
            siticoneButtonReportCancel.ReadOnlyTextColor = Color.FromArgb(100, 100, 100);
            siticoneButtonReportCancel.RippleColor = Color.FromArgb(0, 0, 0);
            siticoneButtonReportCancel.RippleRadiusMultiplier = 0.6F;
            siticoneButtonReportCancel.ShadowBlur = 5;
            siticoneButtonReportCancel.ShadowColor = Color.FromArgb(30, 0, 0, 0);
            siticoneButtonReportCancel.ShadowOffset = new Point(0, 2);
            siticoneButtonReportCancel.ShakeDuration = 500;
            siticoneButtonReportCancel.ShakeIntensity = 5;
            siticoneButtonReportCancel.Size = new Size(275, 39);
            siticoneButtonReportCancel.TabIndex = 8;
            siticoneButtonReportCancel.Text = "Cancel";
            siticoneButtonReportCancel.TextAlign = ContentAlignment.MiddleCenter;
            siticoneButtonReportCancel.TextColor = Color.FromArgb(0, 0, 0);
            siticoneButtonReportCancel.TooltipText = null;
            siticoneButtonReportCancel.UseAdvancedRendering = true;
            siticoneButtonReportCancel.UseParticles = false;
            siticoneButtonReportCancel.Click += siticoneButtonReportCancel_Click;
            // 
            // siticoneLabelReportSummary
            // 
            siticoneLabelReportSummary.BackColor = Color.Transparent;
            siticoneLabelReportSummary.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            siticoneLabelReportSummary.Location = new Point(385, 9);
            siticoneLabelReportSummary.Name = "siticoneLabelReportSummary";
            siticoneLabelReportSummary.Size = new Size(70, 23);
            siticoneLabelReportSummary.TabIndex = 9;
            siticoneLabelReportSummary.Text = "Summary";
            // 
            // siticoneDGVReportSummary
            // 
            siticoneDGVReportSummary.BackColor = Color.FromArgb(45, 45, 48);
            siticoneDGVReportSummary.CellFont = new Font("Segoe UI", 8.25F, FontStyle.Regular, GraphicsUnit.Point, 0);
            siticoneDGVReportSummary.DataSource = null;
            siticoneDGVReportSummary.HeaderFont = new Font("Segoe UI", 10F, FontStyle.Bold);
            siticoneDGVReportSummary.Location = new Point(385, 35);
            siticoneDGVReportSummary.Name = "siticoneDGVReportSummary";
            siticoneDGVReportSummary.Size = new Size(631, 565);
            siticoneDGVReportSummary.TabIndex = 10;
            // 
            // siticoneTextBoxReportTitle
            // 
            siticoneTextBoxReportTitle.AccessibleDescription = "A customizable text input field.";
            siticoneTextBoxReportTitle.AccessibleName = "Text Box";
            siticoneTextBoxReportTitle.AccessibleRole = AccessibleRole.Text;
            siticoneTextBoxReportTitle.BackColor = Color.Transparent;
            siticoneTextBoxReportTitle.BlinkCount = 3;
            siticoneTextBoxReportTitle.BlinkShadow = false;
            siticoneTextBoxReportTitle.BorderColor1 = Color.LightSlateGray;
            siticoneTextBoxReportTitle.BorderColor2 = Color.LightSlateGray;
            siticoneTextBoxReportTitle.BorderFocusColor1 = Color.FromArgb(77, 77, 255);
            siticoneTextBoxReportTitle.BorderFocusColor2 = Color.FromArgb(77, 77, 255);
            siticoneTextBoxReportTitle.CanShake = true;
            siticoneTextBoxReportTitle.ContinuousBlink = false;
            siticoneTextBoxReportTitle.CursorBlinkRate = 500;
            siticoneTextBoxReportTitle.CursorColor = Color.Black;
            siticoneTextBoxReportTitle.CursorHeight = 26;
            siticoneTextBoxReportTitle.CursorOffset = 0;
            siticoneTextBoxReportTitle.CursorStyle = SiticoneNetCoreUI.Helpers.DrawingStyle.SiticoneDrawingStyle.Solid;
            siticoneTextBoxReportTitle.CursorWidth = 1;
            siticoneTextBoxReportTitle.DisabledBackColor = Color.WhiteSmoke;
            siticoneTextBoxReportTitle.DisabledBorderColor = Color.LightGray;
            siticoneTextBoxReportTitle.DisabledTextColor = Color.Gray;
            siticoneTextBoxReportTitle.EnableDropShadow = false;
            siticoneTextBoxReportTitle.FillColor1 = Color.White;
            siticoneTextBoxReportTitle.FillColor2 = Color.White;
            siticoneTextBoxReportTitle.Font = new Font("Segoe UI", 9.5F);
            siticoneTextBoxReportTitle.ForeColor = Color.DimGray;
            siticoneTextBoxReportTitle.HoverBorderColor1 = Color.Gray;
            siticoneTextBoxReportTitle.HoverBorderColor2 = Color.Gray;
            siticoneTextBoxReportTitle.IsEnabled = true;
            siticoneTextBoxReportTitle.Location = new Point(48, 76);
            siticoneTextBoxReportTitle.Name = "siticoneTextBoxReportTitle";
            siticoneTextBoxReportTitle.PlaceholderColor = Color.Gray;
            siticoneTextBoxReportTitle.PlaceholderText = "Enter text here...";
            siticoneTextBoxReportTitle.ReadOnlyBorderColor1 = Color.LightGray;
            siticoneTextBoxReportTitle.ReadOnlyBorderColor2 = Color.LightGray;
            siticoneTextBoxReportTitle.ReadOnlyFillColor1 = Color.WhiteSmoke;
            siticoneTextBoxReportTitle.ReadOnlyFillColor2 = Color.WhiteSmoke;
            siticoneTextBoxReportTitle.ReadOnlyPlaceholderColor = Color.DarkGray;
            siticoneTextBoxReportTitle.SelectionBackColor = Color.FromArgb(77, 77, 255);
            siticoneTextBoxReportTitle.ShadowAnimationDuration = 1;
            siticoneTextBoxReportTitle.ShadowBlur = 10;
            siticoneTextBoxReportTitle.ShadowColor = Color.FromArgb(15, 0, 0, 0);
            siticoneTextBoxReportTitle.Size = new Size(275, 40);
            siticoneTextBoxReportTitle.SolidBorderColor = Color.LightSlateGray;
            siticoneTextBoxReportTitle.SolidBorderFocusColor = Color.FromArgb(77, 77, 255);
            siticoneTextBoxReportTitle.SolidBorderHoverColor = Color.Gray;
            siticoneTextBoxReportTitle.SolidFillColor = Color.White;
            siticoneTextBoxReportTitle.TabIndex = 11;
            siticoneTextBoxReportTitle.TextPadding = new Padding(16, 0, 6, 0);
            siticoneTextBoxReportTitle.ValidationErrorMessage = "Invalid input.";
            siticoneTextBoxReportTitle.ValidationFunction = null;
            // 
            // siticoneLabelReportTitle
            // 
            siticoneLabelReportTitle.BackColor = Color.Transparent;
            siticoneLabelReportTitle.Font = new Font("Segoe UI", 10F);
            siticoneLabelReportTitle.Location = new Point(48, 50);
            siticoneLabelReportTitle.Name = "siticoneLabelReportTitle";
            siticoneLabelReportTitle.Size = new Size(100, 23);
            siticoneLabelReportTitle.TabIndex = 12;
            siticoneLabelReportTitle.Text = "Report Title";
            // 
            // siticoneDateTimePickerReportEndDate
            // 
            siticoneDateTimePickerReportEndDate.AutoScaleFonts = true;
            siticoneDateTimePickerReportEndDate.BackColor = Color.Transparent;
            siticoneDateTimePickerReportEndDate.BaseCalendarFormSize = new Size(535, 460);
            siticoneDateTimePickerReportEndDate.BorderColor = Color.FromArgb(180, 180, 180);
            siticoneDateTimePickerReportEndDate.BorderWidth = 2;
            siticoneDateTimePickerReportEndDate.BottomLeftBorderRadius = 8;
            siticoneDateTimePickerReportEndDate.BottomRightBorderRadius = 8;
            siticoneDateTimePickerReportEndDate.CalendarBackgroundColor = Color.White;
            siticoneDateTimePickerReportEndDate.CalendarChevronColor = Color.Gray;
            siticoneDateTimePickerReportEndDate.CalendarChevronHoverColor = Color.Blue;
            siticoneDateTimePickerReportEndDate.CalendarDayButtonBackColor = Color.White;
            siticoneDateTimePickerReportEndDate.CalendarDayButtonForeColor = Color.Black;
            siticoneDateTimePickerReportEndDate.CalendarDayHeaderBackColor = Color.White;
            siticoneDateTimePickerReportEndDate.CalendarDayHeaderForeColor = Color.FromArgb(100, 100, 100);
            siticoneDateTimePickerReportEndDate.CalendarDayLabelFont = new Font("Segoe UI", 10F, FontStyle.Bold);
            siticoneDateTimePickerReportEndDate.CalendarDisabledDateBackColor = Color.LightGray;
            siticoneDateTimePickerReportEndDate.CalendarDisabledDateForeColor = Color.DarkGray;
            siticoneDateTimePickerReportEndDate.CalendarFormAnimationSpeed = 15;
            siticoneDateTimePickerReportEndDate.CalendarFormAnimationStep = 0.08D;
            siticoneDateTimePickerReportEndDate.CalendarFormBackColor = Color.White;
            siticoneDateTimePickerReportEndDate.CalendarFormBorderColor = Color.FromArgb(220, 220, 220);
            siticoneDateTimePickerReportEndDate.CalendarFormBorderWidth = 2;
            siticoneDateTimePickerReportEndDate.CalendarFormCornerRadius = 2;
            siticoneDateTimePickerReportEndDate.CalendarFormFadeOutStep = 0.1D;
            siticoneDateTimePickerReportEndDate.CalendarFormHeight = 460;
            siticoneDateTimePickerReportEndDate.CalendarFormShadowColor = Color.FromArgb(50, 0, 0, 0);
            siticoneDateTimePickerReportEndDate.CalendarFormShadowDepth = 5;
            siticoneDateTimePickerReportEndDate.CalendarFormWidth = 535;
            siticoneDateTimePickerReportEndDate.CalendarGridMargin = new Padding(8);
            siticoneDateTimePickerReportEndDate.CalendarGridPadding = new Padding(5);
            siticoneDateTimePickerReportEndDate.CalendarLockedDateBackColor = Color.LightGray;
            siticoneDateTimePickerReportEndDate.CalendarLockedDateForeColor = Color.DarkGray;
            siticoneDateTimePickerReportEndDate.CalendarLockedDates = (List<DateTime>)resources.GetObject("siticoneDateTimePickerReportEndDate.CalendarLockedDates");
            siticoneDateTimePickerReportEndDate.CalendarMargin = 5;
            siticoneDateTimePickerReportEndDate.CalendarMaxDate = new DateTime(9998, 12, 31, 0, 0, 0, 0);
            siticoneDateTimePickerReportEndDate.CalendarMaxYear = 2125;
            siticoneDateTimePickerReportEndDate.CalendarMinDate = new DateTime(1753, 1, 1, 0, 0, 0, 0);
            siticoneDateTimePickerReportEndDate.CalendarMinYear = 1925;
            siticoneDateTimePickerReportEndDate.CalendarRangeDateBackColor = Color.LightBlue;
            siticoneDateTimePickerReportEndDate.CalendarRangeEndDateBackColor = Color.DodgerBlue;
            siticoneDateTimePickerReportEndDate.CalendarRangeSelectedForeColor = Color.Black;
            siticoneDateTimePickerReportEndDate.CalendarRangeStartDateBackColor = Color.DodgerBlue;
            siticoneDateTimePickerReportEndDate.CalendarSelectedDateBackColor = Color.FromArgb(0, 120, 215);
            siticoneDateTimePickerReportEndDate.CalendarSelectedDateForeColor = Color.White;
            siticoneDateTimePickerReportEndDate.CalendarSelectionMode = SiticoneNetCoreUI.SelectionMode.Range;
            siticoneDateTimePickerReportEndDate.CalendarTodayBackColor = Color.White;
            siticoneDateTimePickerReportEndDate.CalendarTodayForeColor = Color.Black;
            siticoneDateTimePickerReportEndDate.CalendarYearPickerHeight = 10;
            siticoneDateTimePickerReportEndDate.CanBeep = true;
            siticoneDateTimePickerReportEndDate.CanShake = true;
            siticoneDateTimePickerReportEndDate.ChevronColor = Color.FromArgb(100, 100, 100);
            siticoneDateTimePickerReportEndDate.ChevronHoverBackColor = Color.FromArgb(220, 225, 245);
            siticoneDateTimePickerReportEndDate.ChevronHoverColor = Color.FromArgb(50, 50, 50);
            siticoneDateTimePickerReportEndDate.ChevronPanelBorderRadius = 0;
            siticoneDateTimePickerReportEndDate.ChevronPanelHeight = 32;
            siticoneDateTimePickerReportEndDate.ChevronPenThickness = 1.8F;
            siticoneDateTimePickerReportEndDate.ChevronRightMargin = 18;
            siticoneDateTimePickerReportEndDate.ChevronSize = new Size(9, 14);
            siticoneDateTimePickerReportEndDate.ChevronStep = 15F;
            siticoneDateTimePickerReportEndDate.ChevronTimerInterval = 15;
            siticoneDateTimePickerReportEndDate.ClearIconColor = Color.Gray;
            siticoneDateTimePickerReportEndDate.ClearIconHoverColor = Color.Red;
            siticoneDateTimePickerReportEndDate.ClearIconRightMargin = 48;
            siticoneDateTimePickerReportEndDate.ClearIconSize = 11;
            siticoneDateTimePickerReportEndDate.ContainerPanelMargin = new Padding(5);
            siticoneDateTimePickerReportEndDate.ContainerPanelPadding = new Padding(0);
            siticoneDateTimePickerReportEndDate.CustomDateFormat = "d";
            siticoneDateTimePickerReportEndDate.CustomDateFormatter = null;
            siticoneDateTimePickerReportEndDate.DateFormat = SiticoneNetCoreUI.DateFormat.LongDate;
            siticoneDateTimePickerReportEndDate.DayButtonBorderRadius = 0;
            siticoneDateTimePickerReportEndDate.DayButtonClickBackColor = Color.FromArgb(220, 230, 250);
            siticoneDateTimePickerReportEndDate.DayButtonFont = new Font("Segoe UI", 10.5F);
            siticoneDateTimePickerReportEndDate.DayButtonHoverBackColor = Color.FromArgb(240, 245, 255);
            siticoneDateTimePickerReportEndDate.DayButtonHoverForeColor = Color.Black;
            siticoneDateTimePickerReportEndDate.DayButtonMargin = new Padding(3);
            siticoneDateTimePickerReportEndDate.DayButtonRowHeight = 16.66F;
            siticoneDateTimePickerReportEndDate.DayHeaderFont = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            siticoneDateTimePickerReportEndDate.DayHeaderForeColor = Color.FromArgb(100, 100, 100);
            siticoneDateTimePickerReportEndDate.DayHeaderMargin = new Padding(1, 1, 1, 8);
            siticoneDateTimePickerReportEndDate.DayHeaderRowHeight = 30F;
            siticoneDateTimePickerReportEndDate.DisabledDayFont = new Font("Segoe UI", 10F, FontStyle.Italic);
            siticoneDateTimePickerReportEndDate.DropdownBackColor = Color.White;
            siticoneDateTimePickerReportEndDate.DropdownFont = new Font("Segoe UI", 11F);
            siticoneDateTimePickerReportEndDate.DropdownHeight = 250;
            siticoneDateTimePickerReportEndDate.FillColor = Color.White;
            siticoneDateTimePickerReportEndDate.FirstDayOfWeek = DayOfWeek.Sunday;
            siticoneDateTimePickerReportEndDate.Font = new Font("Segoe UI", 10F);
            siticoneDateTimePickerReportEndDate.ForeColor = Color.FromArgb(50, 50, 50);
            siticoneDateTimePickerReportEndDate.GradientEndColor = Color.Gray;
            siticoneDateTimePickerReportEndDate.GradientStartColor = Color.White;
            siticoneDateTimePickerReportEndDate.HighlightWeekends = true;
            siticoneDateTimePickerReportEndDate.IconSize = 16;
            siticoneDateTimePickerReportEndDate.IsReadonly = false;
            siticoneDateTimePickerReportEndDate.Location = new Point(48, 365);
            siticoneDateTimePickerReportEndDate.LockedDates = (List<DateTime>)resources.GetObject("siticoneDateTimePickerReportEndDate.LockedDates");
            siticoneDateTimePickerReportEndDate.MakeRadial = false;
            siticoneDateTimePickerReportEndDate.MaxDate = new DateTime(9998, 12, 31, 0, 0, 0, 0);
            siticoneDateTimePickerReportEndDate.MaxFontScale = 1.8F;
            siticoneDateTimePickerReportEndDate.MinDate = new DateTime(1753, 1, 1, 0, 0, 0, 0);
            siticoneDateTimePickerReportEndDate.MinFontScale = 0.4F;
            siticoneDateTimePickerReportEndDate.MinimumFormSize = new Size(150, 150);
            siticoneDateTimePickerReportEndDate.MonthChevronPanelMargin = new Padding(4, 17, 4, 0);
            siticoneDateTimePickerReportEndDate.MonthChevronSpacing = 5;
            siticoneDateTimePickerReportEndDate.MonthComboBoxMargin = new Padding(0, 17, 5, 0);
            siticoneDateTimePickerReportEndDate.MonthComboBoxSize = new Size(130, 30);
            siticoneDateTimePickerReportEndDate.Name = "siticoneDateTimePickerReportEndDate";
            siticoneDateTimePickerReportEndDate.NavigationFlowPadding = new Padding(12, 0, 12, 0);
            siticoneDateTimePickerReportEndDate.NavigationPanelBackColor = Color.FromArgb(245, 245, 245);
            siticoneDateTimePickerReportEndDate.NavigationPanelHeight = 65;
            siticoneDateTimePickerReportEndDate.NextMonthPanelWidth = 34;
            siticoneDateTimePickerReportEndDate.NextYearPanelWidth = 40;
            siticoneDateTimePickerReportEndDate.PlaceholderText = "Select a date...";
            siticoneDateTimePickerReportEndDate.PrevMonthPanelWidth = 34;
            siticoneDateTimePickerReportEndDate.PrevYearPanelWidth = 40;
            siticoneDateTimePickerReportEndDate.RangeStartEndCornerRadius = 0;
            siticoneDateTimePickerReportEndDate.ReadonlyBorderColor = Color.Gray;
            siticoneDateTimePickerReportEndDate.ReadonlyFillColor = Color.LightGray;
            siticoneDateTimePickerReportEndDate.ReadOnlyForeColor = Color.DarkGray;
            siticoneDateTimePickerReportEndDate.ReadonlyPlaceHolderColor = Color.DarkGray;
            siticoneDateTimePickerReportEndDate.SelectedDate = null;
            siticoneDateTimePickerReportEndDate.SelectedDateBorderColor = Color.Black;
            siticoneDateTimePickerReportEndDate.SelectedDateBorderThickness = 1F;
            siticoneDateTimePickerReportEndDate.SelectedDates = (List<DateTime>)resources.GetObject("siticoneDateTimePickerReportEndDate.SelectedDates");
            siticoneDateTimePickerReportEndDate.SelectionMode = SiticoneNetCoreUI.SelectionMode.Range;
            siticoneDateTimePickerReportEndDate.ShakeAmplitude = 4;
            siticoneDateTimePickerReportEndDate.ShakeTimerInterval = 30;
            siticoneDateTimePickerReportEndDate.ShakeTotalShakes = 8;
            siticoneDateTimePickerReportEndDate.ShowClearButton = true;
            siticoneDateTimePickerReportEndDate.ShowMonthYearNavigation = true;
            siticoneDateTimePickerReportEndDate.ShowTodayButton = true;
            siticoneDateTimePickerReportEndDate.Size = new Size(275, 45);
            siticoneDateTimePickerReportEndDate.TabIndex = 13;
            siticoneDateTimePickerReportEndDate.Text = "siticoneDateTimePickerEndDate";
            siticoneDateTimePickerReportEndDate.TodayBorderColor = Color.Black;
            siticoneDateTimePickerReportEndDate.TodayBorderThickness = 2F;
            siticoneDateTimePickerReportEndDate.TodayButtonBackColor = Color.FromArgb(0, 120, 215);
            siticoneDateTimePickerReportEndDate.TodayButtonBorderRadius = 0;
            siticoneDateTimePickerReportEndDate.TodayButtonClickBackColor = Color.Black;
            siticoneDateTimePickerReportEndDate.TodayButtonFont = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            siticoneDateTimePickerReportEndDate.TodayButtonForeColor = Color.White;
            siticoneDateTimePickerReportEndDate.TodayButtonHoverBackColor = Color.FromArgb(0, 100, 190);
            siticoneDateTimePickerReportEndDate.TodayButtonMargin = new Padding(0, 17, 15, 0);
            siticoneDateTimePickerReportEndDate.TodayButtonSize = new Size(70, 35);
            siticoneDateTimePickerReportEndDate.TodayButtonText = "Today";
            siticoneDateTimePickerReportEndDate.TodayTextColor = Color.Black;
            siticoneDateTimePickerReportEndDate.TodayTextFont = new Font("Segoe UI", 10F, FontStyle.Bold);
            siticoneDateTimePickerReportEndDate.TopLeftBorderRadius = 8;
            siticoneDateTimePickerReportEndDate.TopRightBorderRadius = 8;
            siticoneDateTimePickerReportEndDate.UseCalendarFormAnimation = true;
            siticoneDateTimePickerReportEndDate.UseCalendarFormShadow = true;
            siticoneDateTimePickerReportEndDate.UseChevronAnimation = true;
            siticoneDateTimePickerReportEndDate.UseGradientFill = false;
            siticoneDateTimePickerReportEndDate.Value = null;
            siticoneDateTimePickerReportEndDate.WeekendDayBackColor = Color.FromArgb(250, 250, 250);
            siticoneDateTimePickerReportEndDate.WeekendDayForeColor = Color.FromArgb(180, 0, 0);
            siticoneDateTimePickerReportEndDate.YearChevronPanelMargin = new Padding(4, 17, 4, 0);
            siticoneDateTimePickerReportEndDate.YearChevronSpacing = 1;
            siticoneDateTimePickerReportEndDate.YearComboBoxMargin = new Padding(5, 17, 0, 0);
            siticoneDateTimePickerReportEndDate.YearComboBoxSize = new Size(90, 30);
            // 
            // siticoneLabelEndDate
            // 
            siticoneLabelEndDate.BackColor = Color.Transparent;
            siticoneLabelEndDate.Font = new Font("Segoe UI", 10F);
            siticoneLabelEndDate.Location = new Point(48, 339);
            siticoneLabelEndDate.Name = "siticoneLabelEndDate";
            siticoneLabelEndDate.Size = new Size(141, 23);
            siticoneLabelEndDate.TabIndex = 14;
            siticoneLabelEndDate.Text = "End Date";
            // 
            // siticoneMaterialRadioButtonDaily
            // 
            siticoneMaterialRadioButtonDaily.ActiveRadioColor = Color.FromArgb(33, 150, 243);
            siticoneMaterialRadioButtonDaily.AlreadyCheckedRippleColor = Color.FromArgb(97, 97, 97);
            siticoneMaterialRadioButtonDaily.AnimationDuration = 250;
            siticoneMaterialRadioButtonDaily.BackColor = Color.Transparent;
            siticoneMaterialRadioButtonDaily.BorderSize = 2;
            siticoneMaterialRadioButtonDaily.CanBeep = false;
            siticoneMaterialRadioButtonDaily.CanShake = false;
            siticoneMaterialRadioButtonDaily.CheckingRippleColor = Color.FromArgb(33, 150, 243);
            siticoneMaterialRadioButtonDaily.CheckMarkColor = Color.White;
            siticoneMaterialRadioButtonDaily.CheckMarkThickness = 2F;
            siticoneMaterialRadioButtonDaily.CustomFont = new Font("Segoe UI", 9F);
            siticoneMaterialRadioButtonDaily.DisabledColor = Color.FromArgb(176, 176, 176);
            siticoneMaterialRadioButtonDaily.EnableKeyboardSupport = true;
            siticoneMaterialRadioButtonDaily.EnableRippleEffect = true;
            siticoneMaterialRadioButtonDaily.Font = new Font("Segoe UI", 9F);
            siticoneMaterialRadioButtonDaily.IdleRadioBorderColor = Color.FromArgb(97, 97, 97);
            siticoneMaterialRadioButtonDaily.LeftPadding = 10;
            siticoneMaterialRadioButtonDaily.Location = new Point(73, 213);
            siticoneMaterialRadioButtonDaily.Name = "siticoneMaterialRadioButtonDaily";
            siticoneMaterialRadioButtonDaily.RadioButtonSize = 18;
            siticoneMaterialRadioButtonDaily.ReadOnly = false;
            siticoneMaterialRadioButtonDaily.ReadOnlyColor = Color.FromArgb(220, 220, 220);
            siticoneMaterialRadioButtonDaily.RippleOpacity = 80;
            siticoneMaterialRadioButtonDaily.RippleSizeMultiplier = 2;
            siticoneMaterialRadioButtonDaily.ShakeDuration = 400;
            siticoneMaterialRadioButtonDaily.ShakeIntensity = 5;
            siticoneMaterialRadioButtonDaily.Size = new Size(75, 40);
            siticoneMaterialRadioButtonDaily.Style = SiticoneNetCoreUI.RadioButtonStyle.Outlined;
            siticoneMaterialRadioButtonDaily.TabIndex = 15;
            siticoneMaterialRadioButtonDaily.Text = "Daily";
            siticoneMaterialRadioButtonDaily.TextColor = Color.FromArgb(33, 33, 33);
            siticoneMaterialRadioButtonDaily.CheckedChanged += siticoneMaterialRadioButtonDaily_CheckedChanged;
            // 
            // siticoneMaterialRadioButtonMonthlyYearly
            // 
            siticoneMaterialRadioButtonMonthlyYearly.ActiveRadioColor = Color.FromArgb(33, 150, 243);
            siticoneMaterialRadioButtonMonthlyYearly.AlreadyCheckedRippleColor = Color.FromArgb(97, 97, 97);
            siticoneMaterialRadioButtonMonthlyYearly.AnimationDuration = 250;
            siticoneMaterialRadioButtonMonthlyYearly.BackColor = Color.Transparent;
            siticoneMaterialRadioButtonMonthlyYearly.BorderSize = 2;
            siticoneMaterialRadioButtonMonthlyYearly.CanBeep = false;
            siticoneMaterialRadioButtonMonthlyYearly.CanShake = false;
            siticoneMaterialRadioButtonMonthlyYearly.CheckingRippleColor = Color.FromArgb(33, 150, 243);
            siticoneMaterialRadioButtonMonthlyYearly.CheckMarkColor = Color.White;
            siticoneMaterialRadioButtonMonthlyYearly.CheckMarkThickness = 2F;
            siticoneMaterialRadioButtonMonthlyYearly.CustomFont = new Font("Segoe UI", 9F);
            siticoneMaterialRadioButtonMonthlyYearly.DisabledColor = Color.FromArgb(176, 176, 176);
            siticoneMaterialRadioButtonMonthlyYearly.EnableKeyboardSupport = true;
            siticoneMaterialRadioButtonMonthlyYearly.EnableRippleEffect = true;
            siticoneMaterialRadioButtonMonthlyYearly.Font = new Font("Segoe UI", 9F);
            siticoneMaterialRadioButtonMonthlyYearly.IdleRadioBorderColor = Color.FromArgb(97, 97, 97);
            siticoneMaterialRadioButtonMonthlyYearly.LeftPadding = 10;
            siticoneMaterialRadioButtonMonthlyYearly.Location = new Point(168, 213);
            siticoneMaterialRadioButtonMonthlyYearly.Name = "siticoneMaterialRadioButtonMonthlyYearly";
            siticoneMaterialRadioButtonMonthlyYearly.RadioButtonSize = 18;
            siticoneMaterialRadioButtonMonthlyYearly.ReadOnly = false;
            siticoneMaterialRadioButtonMonthlyYearly.ReadOnlyColor = Color.FromArgb(220, 220, 220);
            siticoneMaterialRadioButtonMonthlyYearly.RippleOpacity = 80;
            siticoneMaterialRadioButtonMonthlyYearly.RippleSizeMultiplier = 2;
            siticoneMaterialRadioButtonMonthlyYearly.ShakeDuration = 400;
            siticoneMaterialRadioButtonMonthlyYearly.ShakeIntensity = 5;
            siticoneMaterialRadioButtonMonthlyYearly.Size = new Size(137, 40);
            siticoneMaterialRadioButtonMonthlyYearly.Style = SiticoneNetCoreUI.RadioButtonStyle.Outlined;
            siticoneMaterialRadioButtonMonthlyYearly.TabIndex = 16;
            siticoneMaterialRadioButtonMonthlyYearly.Text = "Monthly / Yearly";
            siticoneMaterialRadioButtonMonthlyYearly.TextColor = Color.FromArgb(33, 33, 33);
            siticoneMaterialRadioButtonMonthlyYearly.CheckedChanged += siticoneMaterialRadioButtonMonthlyYearly_CheckedChanged;
            // 
            // ReportForm
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1018, 597);
            Controls.Add(siticoneMaterialRadioButtonMonthlyYearly);
            Controls.Add(siticoneMaterialRadioButtonDaily);
            Controls.Add(siticoneLabelEndDate);
            Controls.Add(siticoneDateTimePickerReportEndDate);
            Controls.Add(siticoneLabelReportTitle);
            Controls.Add(siticoneTextBoxReportTitle);
            Controls.Add(siticoneDGVReportSummary);
            Controls.Add(siticoneLabelReportSummary);
            Controls.Add(siticoneButtonReportCancel);
            Controls.Add(siticoneButtonExportReport);
            Controls.Add(siticoneButtonReportGenerate);
            Controls.Add(siticoneDateTimePickerReportStartDate);
            Controls.Add(siticoneLabelReportRangeDate);
            Controls.Add(siticoneDropdownReportType);
            Controls.Add(siticoneLabelReportType);
            Controls.Add(siticoneLabelReportDetails);
            Name = "ReportForm";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "ReportForm";
            Load += ReportForm_Load;
            ((System.ComponentModel.ISupportInitialize)siticoneDGVReportSummary).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private SiticoneNetCoreUI.SiticoneLabel siticoneLabelReportDetails;
        private SiticoneNetCoreUI.SiticoneLabel siticoneLabelReportType;
        private SiticoneNetCoreUI.SiticoneDropdown siticoneDropdownReportType;
        private SiticoneNetCoreUI.SiticoneLabel siticoneLabelReportRangeDate;
        private SiticoneNetCoreUI.SiticoneDateTimePicker siticoneDateTimePickerReportStartDate;
        private SiticoneNetCoreUI.SiticoneButton siticoneButtonReportGenerate;
        private SiticoneNetCoreUI.SiticoneButton siticoneButtonExportReport;
        private SiticoneNetCoreUI.SiticoneButton siticoneButtonReportCancel;
        private SiticoneNetCoreUI.SiticoneLabel siticoneLabelReportSummary;
        private SiticoneNetCoreUI.SiticoneDataGridView siticoneDGVReportSummary;
        private SiticoneNetCoreUI.SiticoneTextBox siticoneTextBoxReportTitle;
        private SiticoneNetCoreUI.SiticoneLabel siticoneLabelReportTitle;
        private SiticoneNetCoreUI.SiticoneDateTimePicker siticoneDateTimePickerReportEndDate;
        private SiticoneNetCoreUI.SiticoneLabel siticoneLabelEndDate;
        private SiticoneNetCoreUI.SiticoneMaterialRadioButton siticoneMaterialRadioButtonDaily;
        private SiticoneNetCoreUI.SiticoneMaterialRadioButton siticoneMaterialRadioButtonMonthlyYearly;
    }
}